[tool.poetry]
name = "cais-spade-llm"
version = "0.1.0"
description = ""
authors = ["Jonghan Lim <jxl567@psu.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
spade = "^4.1.2"
spade-llm = "^0.2.0"
langchain = "^0.2.11"
langchain-community = "^0.2.10"
langchain-openai = "^0.1.14"
pdfplumber = "^0.11.2"
chroma = "^0.2.0"
chromadb = "^0.5.5"
ltlf2dfa = "^1.0.2"
python-dotenv = "^1.2.1"
graphviz = "^0.21"
pytest = "^9.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
