/KMR/controller_manager:
  ros__parameters:
    update_rate: 225
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    KMR_iiwa_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    KMR_rg2_gripper_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController

/KMR/KMR_iiwa_joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0

/KMR/KMR_rg2_gripper_traj_controller:
  ros__parameters:
    joints:
      - KMR_rg2_finger_width
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
