"""Spec2Primitives PA context-interaction boundary."""

from cais_spade_llm.spec2primitives.agents.pa.context_assessment import (
    cancel_pa_context_interaction,
    continue_pa_context_interaction,
    submit_pa_clarification_reply,
)
from cais_spade_llm.spec2primitives.agents.pa.context_grounding import (
    PAOntologyConfig,
    ProductContextGroundingRuntime,
)
from cais_spade_llm.spec2primitives.agents.pa.context_interaction import (
    ProductAgentContextRuntime,
    start_pa_context_interaction,
)
from cais_spade_llm.spec2primitives.agents.pa.context_serving import (
    serve_pa_requested_context,
)
from cais_spade_llm.spec2primitives.agents.pa.grounding_contracts import (
    GroundingProducerDescriptor,
    PAContextGroundingCompletionV2,
    PAContextGroundingCompletionV3,
    PAContextGroundingCompletionV4,
    PAContextGroundingCompletionV5,
    PAContextGroundingCompletionV6,
    PAContextGroundingCompletionV7,
    PAContextGroundingCompletionV8,
    ProductContextView,
    TypedContextBinding,
    TypedGroundingContract,
    load_completed_product_context_view,
    load_pa_context_grounding_completion,
)
from cais_spade_llm.spec2primitives.agents.pa.presentation_records import (
    AllocationEvidenceEntry,
    AllocationEvidenceSource,
    AllocationPresentationRecord,
    AllocationResourceEntry,
    EvidencePresentationEntry,
    EvidencePresentationRecord,
    PresentationRecordError,
    load_allocation_presentation,
    load_evidence_presentation,
    load_or_create_allocation_presentation,
    load_or_create_evidence_presentation,
)
from cais_spade_llm.spec2primitives.agents.pa.production_grounding import (
    CameraToWorldCalibrationRuntime,
    ProductionProductContextGroundingRuntime,
)
from cais_spade_llm.spec2primitives.agents.pa.resource_grounding import (
    CartesianReachabilityRequest,
    CartesianStateEvidence,
    ReachabilityCheckRecord,
    ResourceGroundingError,
    ResourceSelectionRecord,
    RobotFrameLocationEvidenceError,
    StateReachEvidence,
    candidate_resource_catalog,
    check_resource_reachability,
    commit_resource_assignment,
    persist_cartesian_reachability,
    persist_pa_resource_selection,
    prepare_cartesian_reachability,
)

__all__ = [
    "ProductAgentContextRuntime",
    "CameraToWorldCalibrationRuntime",
    "CartesianReachabilityRequest",
    "CartesianStateEvidence",
    "ReachabilityCheckRecord",
    "GroundingProducerDescriptor",
    "AllocationEvidenceEntry",
    "AllocationEvidenceSource",
    "AllocationPresentationRecord",
    "AllocationResourceEntry",
    "EvidencePresentationEntry",
    "EvidencePresentationRecord",
    "PAOntologyConfig",
    "PAContextGroundingCompletionV2",
    "PAContextGroundingCompletionV3",
    "PAContextGroundingCompletionV4",
    "PAContextGroundingCompletionV5",
    "PAContextGroundingCompletionV6",
    "PAContextGroundingCompletionV7",
    "PAContextGroundingCompletionV8",
    "ProductContextView",
    "ProductContextGroundingRuntime",
    "ProductionProductContextGroundingRuntime",
    "PresentationRecordError",
    "ResourceGroundingError",
    "ResourceSelectionRecord",
    "RobotFrameLocationEvidenceError",
    "StateReachEvidence",
    "TypedContextBinding",
    "TypedGroundingContract",
    "cancel_pa_context_interaction",
    "candidate_resource_catalog",
    "check_resource_reachability",
    "continue_pa_context_interaction",
    "commit_resource_assignment",
    "load_completed_product_context_view",
    "load_allocation_presentation",
    "load_evidence_presentation",
    "load_or_create_allocation_presentation",
    "load_or_create_evidence_presentation",
    "load_pa_context_grounding_completion",
    "persist_pa_resource_selection",
    "persist_cartesian_reachability",
    "prepare_cartesian_reachability",
    "serve_pa_requested_context",
    "start_pa_context_interaction",
    "submit_pa_clarification_reply",
]
