"""OpenAI-backed document evidence interpretation boundary."""

from cais_spade_llm.spec2primitives.tools.document_evidence.diagnostic import (
    run_document_interpretation_diagnostic,
)
from cais_spade_llm.spec2primitives.tools.document_evidence.interpreter import (
    DOCUMENT_OVERVIEW_SCHEMA_VERSION,
    DOCUMENT_QUERY_SCHEMA_VERSION,
    DOCUMENT_SOURCE_INDEX_SCHEMA_VERSION,
    DocumentInterpretationError,
    DocumentInterpretationResult,
    DocumentOverviewRecord,
    DocumentQueryResult,
    DocumentQueryVisionRequest,
    DocumentSourceIndexRecord,
    DocumentSourceIndexResult,
    DocumentVisionRequest,
    DocumentVisionResponse,
    DocumentVisionRuntime,
    OpenAIDocumentVisionRuntime,
    document_overview_cache_status,
    document_query_schema,
    index_document_evidence,
    interpret_document_evidence,
    prepare_document_overview,
    prepare_document_source_index,
    query_document_evidence,
)

__all__ = [
    "DOCUMENT_OVERVIEW_SCHEMA_VERSION",
    "DOCUMENT_QUERY_SCHEMA_VERSION",
    "DOCUMENT_SOURCE_INDEX_SCHEMA_VERSION",
    "DocumentInterpretationError",
    "DocumentInterpretationResult",
    "DocumentOverviewRecord",
    "DocumentQueryResult",
    "DocumentQueryVisionRequest",
    "DocumentSourceIndexRecord",
    "DocumentSourceIndexResult",
    "DocumentVisionRequest",
    "DocumentVisionResponse",
    "DocumentVisionRuntime",
    "OpenAIDocumentVisionRuntime",
    "document_query_schema",
    "document_overview_cache_status",
    "index_document_evidence",
    "interpret_document_evidence",
    "prepare_document_source_index",
    "prepare_document_overview",
    "query_document_evidence",
    "run_document_interpretation_diagnostic",
]
